---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cv-image-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: ugwulo/cv-image:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector: 
    app: nginx
  type: LoadBalancer

# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: cv-ingress
#   annotations:
#     kubernetes.io/ingress.global-static-ip-name: nginxcv
# spec:
#   rules:
#     - host: cv.ugwulo.me
#       http:
#         paths:
#           - path: /
#             backend:
#               serviceName: nginx-svc
#               servicePort: 80
# ---
# apiVersion: networking.gke.io/v1
# kind: ManagedCertificate
# metadata:
#   name: managed-cert
# spec:
#   domains:
#     - cv.ugwulo.me
#     - altschool.ugwulo.me